image: maven:3.6.3-jdk-11

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  tags:
    - docker
  script:
    - mvn clean compile site
  artifacts:
    paths:
      - target/site
