image: maven:3.6.3-jdk-11

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  tags:
    - docker
  script:
    - mvn clean compile site
    - "echo -n 'Total Coverage: '; cat target/site/jacoco/index.html | egrep -o '([0-9]{1,3})%' | tail -1"
  coverage: '/Total Coverage: ([0-9]{1,3})%/'
  artifacts:
    paths:
      - target/site
